In [68]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [69]:
from pathlib import Path

In [70]:
pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", "{:.2f}".format)

In [71]:
from pathlib import Path

DATA_PATH = Path("../data/raw/ecommerce-sales1.csv")

df = pd.read_csv(DATA_PATH)

df.head()

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount,sales,profit,payment_method,ship_mode,order_status
0,ORD-1000,2026-01-01,CUS-1000,PRO-1000,1056,71.00,57.00,36.00,43.00,payment_method_98,ship_mode_63,order_status_84
1,ORD-1001,2026-02-02,CUS-1001,PRO-1001,1138,87.50,73.50,52.50,59.50,payment_method_11,ship_mode_76,order_status_97
2,ORD-1002,2026-03-03,CUS-1002,PRO-1002,1246,104.00,90.00,69.00,76.00,payment_method_24,ship_mode_89,order_status_10
3,ORD-1003,2026-04-04,CUS-1003,PRO-1003,1380,20.50,106.50,85.50,92.50,payment_method_37,ship_mode_2,order_status_23
4,ORD-1004,2026-05-05,CUS-1004,PRO-1004,1040,37.00,23.00,102.00,109.00,payment_method_50,ship_mode_15,order_status_36

In [1]:
df.groupby("Product")["Revenue"].sum()

NameError: name 'df' is not defined

In [72]:
df.shape
df.head()
df.tail()
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        25 non-null     str
 1   order_date      25 non-null     str
 2   customer_id     25 non-null     str
 3   product_id      25 non-null     str
 4   quantity        25 non-null     int64
 5   unit_price      25 non-null     float64
 6   discount        25 non-null     float64
 7   sales           25 non-null     float64
 8   profit          25 non-null     float64
 9   payment_method  25 non-null     str
 10  ship_mode       25 non-null     str
 11  order_status    25 non-null     str
dtypes: float64(4), int64(1), str(7)
memory usage: 2.5 KB

       quantity  unit_price  discount  sales  profit
count     25.00       25.00     25.00  25.00   25.00
mean    1644.00       93.00     95.00  90.00   93.00
std      518.83       38.31     35.25  37.93   34.72
min     1040.00       20.50     23.00  18.50   25.50
25%     1238.00       69.00     71.50  67.00   73.00
50%     1540.00       87.50     90.00  85.50   91.50
75%     1966.00      118.50    121.00 116.50  122.50
max     2710.00      167.00    154.00 166.00  156.50

In [73]:
df.describe(include = "all")

,order_id,order_date,customer_id,product_id,quantity,unit_price,discount,sales,profit,payment_method,ship_mode,order_status
count,25,25,25,25,25.00,25.00,25.00,25.00,25.00,25,25,25
unique,25,25,25,25,NaN,NaN,NaN,NaN,NaN,25,25,25
top,ORD-1000,2026-01-01,CUS-1000,PRO-1000,NaN,NaN,NaN,NaN,NaN,payment_method_98,ship_mode_63,order_status_84
freq,1,1,1,1,NaN,NaN,NaN,NaN,NaN,1,1,1
mean,NaN,NaN,NaN,NaN,1644.00,93.00,95.00,90.00,93.00,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,518.83,38.31,35.25,37.93,34.72,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,1040.00,20.50,23.00,18.50,25.50,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,1238.00,69.00,71.50,67.00,73.00,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,1540.00,87.50,90.00,85.50,91.50,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,1966.00,118.50,121.00,116.50,122.50,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,2710.00,167.00,154.00,166.00,156.50,NaN,NaN,NaN

In [74]:
df.columns

Index(['order_id', 'order_date', 'customer_id', 'product_id', 'quantity',
       'unit_price', 'discount', 'sales', 'profit', 'payment_method',
       'ship_mode', 'order_status'],
      dtype='str')

In [75]:
df.isnull().sum()

order_id          0
order_date        0
customer_id       0
product_id        0
quantity          0
unit_price        0
discount          0
sales             0
profit            0
payment_method    0
ship_mode         0
order_status      0
dtype: int64

In [76]:
df.duplicated().sum()

np.int64(0)

In [77]:
df = df.drop_duplicates()

In [78]:
missing = df.isnull().sum()

missing_percentage = (
    df.isnull().sum() / len(df) * 100
).round(2)

missing_report = pd.DataFrame({
    "Missing_Count": missing,
    "Missing_Percentage": missing_percentage
})

missing_report.sort_values(
    "Missing_Percentage",
    ascending=False
)

                Missing_Count  Missing_Percentage
order_id                    0                0.00
order_date                  0                0.00
customer_id                 0                0.00
product_id                  0                0.00
quantity                    0                0.00
unit_price                  0                0.00
discount                    0                0.00
sales                       0                0.00
profit                      0                0.00
payment_method              0                0.00
ship_mode                   0                0.00
order_status                0                0.00

In [79]:
# proper missing value report 
missing_count = df.isnull().sum()

missing_percentage = (
    df.isnull().sum() / len(df) * 100
).round(2)

missing_report = pd.DataFrame({
    "Missing_Count": missing_count,
    "Missing_Percentage": missing_percentage
})

missing_report.sort_values(
    "Missing_Percentage",
    ascending=False
)

                Missing_Count  Missing_Percentage
order_id                    0                0.00
order_date                  0                0.00
customer_id                 0                0.00
product_id                  0                0.00
quantity                    0                0.00
unit_price                  0                0.00
discount                    0                0.00
sales                       0                0.00
profit                      0                0.00
payment_method              0                0.00
ship_mode                   0                0.00
order_status                0                0.00

In [80]:
df.duplicated().sum()
df[df.duplicated()]

Empty DataFrame
Columns: [order_id, order_date, customer_id, product_id, quantity, unit_price, discount, sales, profit, payment_method, ship_mode, order_status]
Index: []

In [81]:
df = df.drop_duplicates()

In [82]:
df.dtypes

order_id              str
order_date            str
customer_id           str
product_id            str
quantity            int64
unit_price        float64
discount          float64
sales             float64
profit            float64
payment_method        str
ship_mode             str
order_status          str
dtype: object

In [83]:
df["order_date"].dtype

In [84]:
df["order_date"] = pd.to_datetime(
    df["order_date"],
    errors="coerce"  # so that invalid dates become Nat instead of reasing an error
    
)

In [85]:
df["order_date"].dtype

dtype('<M8[us]')

In [86]:
df["order_date"].isnull().sum()

np.int64(0)

In [87]:
# Step 7 — Clean text columns #

text_columns = [
    "order_id",
    "customer_id",
    "payment_method",
    "ship_mode",
    "order_status"
]
# .str.strip() this removes leading and trailing whitespace from the string values in the specified columns
for col in text_columns:
    df[col] = df[col].astype(str).str.strip()

In [88]:
# Create date features 
#Create date features
#Now that order_date is a proper datetime column, create useful features.
df["year"] = df["order_date"].dt.year
df["month"] = df["order_date"].dt.month
df["month_name"] = df["order_date"].dt.month_name()
df["month_name"] = df["order_date"].dt.month_name()
df["quarter"] = df["order_date"].dt.quarter
df["day"] = df["order_date"].dt.day

df["day_name"] = df["order_date"].dt.day_name()

In [89]:
#Create Year-Month
#This one will be especially useful for our monthly revenue chart.
df["year_month"] = (
    df["order_date"]
    .dt.to_period("M")
    .astype(str)
)

In [90]:
# First we need to see what your actual dataset contains. 

print("Payment Methods:")
print(df["payment_method"].unique())

print("\nShip Modes:")
print(df["ship_mode"].unique())

print("\nOrder Status:")
print(df["order_status"].unique())

Payment Methods:
<StringArray>
['payment_method_98', 'payment_method_11', 'payment_method_24',
 'payment_method_37', 'payment_method_50', 'payment_method_63',
 'payment_method_76', 'payment_method_89',  'payment_method_2',
 'payment_method_15', 'payment_method_28', 'payment_method_41',
 'payment_method_54', 'payment_method_67', 'payment_method_80',
 'payment_method_93',  'payment_method_6', 'payment_method_19',
 'payment_method_32', 'payment_method_45', 'payment_method_58',
 'payment_method_71', 'payment_method_84', 'payment_method_97',
 'payment_method_10']
Length: 25, dtype: str

Ship Modes:
<StringArray>
['ship_mode_63', 'ship_mode_76', 'ship_mode_89',  'ship_mode_2',
 'ship_mode_15', 'ship_mode_28', 'ship_mode_41', 'ship_mode_54',
 'ship_mode_67', 'ship_mode_80', 'ship_mode_93',  'ship_mode_6',
 'ship_mode_19', 'ship_mode_32', 'ship_mode_45', 'ship_mode_58',
 'ship_mode_71', 'ship_mode_84', 'ship_mode_97', 'ship_mode_10',
 'ship_mode_23', 'ship_mode_36', 'ship_mode_49', 'ship_mode_62',
 'ship_mode_75']
Length: 25, dtype: str

Order Status:
<StringArray>
['order_status_84', 'order_status_97', 'order_status_10', 'order_status_23',
 'order_status_36', 'order_status_49', 'order_status_62', 'order_status_75',
 'order_status_88',  'order_status_1', 'order_status_14', 'order_status_27',
 'order_status_40', 'order_status_53', 'order_status_66', 'order_status_79',
 'order_status_92',  'order_status_5', 'order_status_18', 'order_status_31',
 'order_status_44', 'order_status_57', 'order_status_70', 'order_status_83',
 'order_status_96']
Length: 25, dtype: str

In [91]:
# check frequency counts 
print("Payment Method Counts")
print(df["payment_method"].value_counts())

print("\nShip Mode Counts")
print(df["ship_mode"].value_counts())

print("\nOrder Status Counts")
print(df["order_status"].value_counts())

Payment Method Counts
payment_method
payment_method_98    1
payment_method_11    1
payment_method_24    1
payment_method_37    1
payment_method_50    1
payment_method_63    1
payment_method_76    1
payment_method_89    1
payment_method_2     1
payment_method_15    1
payment_method_28    1
payment_method_41    1
payment_method_54    1
payment_method_67    1
payment_method_80    1
payment_method_93    1
payment_method_6     1
payment_method_19    1
payment_method_32    1
payment_method_45    1
payment_method_58    1
payment_method_71    1
payment_method_84    1
payment_method_97    1
payment_method_10    1
Name: count, dtype: int64

Ship Mode Counts
ship_mode
ship_mode_63    1
ship_mode_76    1
ship_mode_89    1
ship_mode_2     1
ship_mode_15    1
ship_mode_28    1
ship_mode_41    1
ship_mode_54    1
ship_mode_67    1
ship_mode_80    1
ship_mode_93    1
ship_mode_6     1
ship_mode_19    1
ship_mode_32    1
ship_mode_45    1
ship_mode_58    1
ship_mode_71    1
ship_mode_84    1
ship_mode_97    1
ship_mode_10    1
ship_mode_23    1
ship_mode_36    1
ship_mode_49    1
ship_mode_62    1
ship_mode_75    1
Name: count, dtype: int64

Order Status Counts
order_status
order_status_84    1
order_status_97    1
order_status_10    1
order_status_23    1
order_status_36    1
order_status_49    1
order_status_62    1
order_status_75    1
order_status_88    1
order_status_1     1
order_status_14    1
order_status_27    1
order_status_40    1
order_status_53    1
order_status_66    1
order_status_79    1
order_status_92    1
order_status_5     1
order_status_18    1
order_status_31    1
order_status_44    1
order_status_57    1
order_status_70    1
order_status_83    1
order_status_96    1
Name: count, dtype: int64

In [92]:
df[df["quantity"] <= 0]

Empty DataFrame
Columns: [order_id, order_date, customer_id, product_id, quantity, unit_price, discount, sales, profit, payment_method, ship_mode, order_status, year, month, month_name, quarter, day, day_name, year_month]
Index: []

In [93]:

df["discount"].describe()

count    25.00
mean     95.00
std      35.25
min      23.00
25%      71.50
50%      90.00
75%     121.00
max     154.00
Name: discount, dtype: float64

In [94]:

df[df["discount"] < 0]

Empty DataFrame
Columns: [order_id, order_date, customer_id, product_id, quantity, unit_price, discount, sales, profit, payment_method, ship_mode, order_status, year, month, month_name, quarter, day, day_name, year_month]
Index: []

In [95]:
df[df["discount"] < 0]

Empty DataFrame
Columns: [order_id, order_date, customer_id, product_id, quantity, unit_price, discount, sales, profit, payment_method, ship_mode, order_status, year, month, month_name, quarter, day, day_name, year_month]
Index: []

In [96]:
# Check Sales and Profit #
df[["sales", "profit"]].describe()

       sales  profit
count  25.00   25.00
mean   90.00   93.00
std    37.93   34.72
min    18.50   25.50
25%    67.00   73.00
50%    85.50   91.50
75%   116.50  122.50
max   166.00  156.50

In [97]:
# Verify the relationship between sales and quantity/price #
df[
    ["quantity", "unit_price", "discount", "sales"]
].head(10)

   quantity  unit_price  discount  sales
0      1056       71.00     57.00  36.00
1      1138       87.50     73.50  52.50
2      1246      104.00     90.00  69.00
3      1380       20.50    106.50  85.50
4      1040       37.00     23.00 102.00
5      1126       53.50     39.50  18.50
6      1238       70.00     56.00  35.00
7      1376       86.50     72.50  51.50
8      1540      103.00     89.00  68.00
9      1730      119.50    105.50  84.50

In [98]:
# Now that order_date is a proper datetime column, create useful features. #
df["year"] = df["order_date"].dt.year

In [99]:
# after doing all this check data quality

data_quality = pd.DataFrame({
    "Column": df.columns,
    "Data_Type": df.dtypes.astype(str),
    "Missing_Values": df.isnull().sum().values,
    "Unique_Values": df.nunique().values
})

data_quality

                        Column       Data_Type  Missing_Values  Unique_Values
order_id              order_id             str               0             25
order_date          order_date  datetime64[us]               0             25
customer_id        customer_id             str               0             25
product_id          product_id             str               0             25
quantity              quantity           int64               0             25
unit_price          unit_price         float64               0             25
discount              discount         float64               0             25
sales                    sales         float64               0             25
profit                  profit         float64               0             25
payment_method  payment_method             str               0             25
ship_mode            ship_mode             str               0             25
order_status      order_status             str               0             25
year                      year           int32               0              1
month                    month           int32               0              9
month_name          month_name             str               0              9
quarter                quarter           int32               0              3
day                        day           int32               0             25
day_name              day_name             str               0              6
year_month          year_month             str               0              9

In [100]:
OUTPUT_PATH = "../data/processed/cleaned_sales.csv"

df.to_csv(
    OUTPUT_PATH,
    index=False
)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!